version: '3.9'

services:
  agent_manager:
    build: 
      context: .
      dockerfile: ./docker/agent_manager/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RUN_ENV=docker
      - PG_USER=postgres
      - PG_PASSWORD=190330Nj#
      - DATABASE=postgres
      - PG_HOST=dobo.c1a8ya0cgjzv.us-east-1.rds.amazonaws.com
      - PG_PORT=5432
      - BROKER_HOST=b-59fc34f8-9d2a-4984-a2de-1de7847dc390.mq.us-east-1.amazonaws.com
      - BROKER_PORT=5671
      - BROKER_USERNAME=dobo
      - BROKER_PASSWORD=190330Dobo#@